using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace AnyRPG {

    /// <summary>
    /// meant to be inherited from by actual network implementations like fish-net, etc.
    /// </summary>
    public abstract class NetworkController : ConfiguredMonoBehaviour {
        
        // client functions
        public virtual bool Login(string username, string password, string server) {
            return false;
        }
        public abstract void RequestLogout();
        public abstract void Disconnect();
        public abstract void RequestSpawnPlayerUnit(string sceneName);
        public abstract void RequestRespawnPlayerUnit();
        public abstract void RequestDespawnPlayerUnit();
        public abstract void RequestRevivePlayerUnit();
        public abstract GameObject RequestSpawnModelPrefab(GameObject prefab, Transform parentTransform, Vector3 position, Vector3 forward);
        public abstract void RequestReturnFromCutscene();
        public abstract bool CanSpawnCharacterOverNetwork();
        public abstract bool OwnPlayer(UnitController unitController);
        public abstract void RequestCreatePlayerCharacter(CharacterSaveData saveData);
        public abstract void DeletePlayerCharacter(int playerCharacterId);
        public abstract void LoadCharacterList();
        public abstract void RequestCreateLobbyGame(string sceneResourceName, bool allowLateJoin);
        public abstract void CancelLobbyGame(int gameId);
        public abstract void JoinLobbyGame(int gameId);
        public abstract void LeaveLobbyGame(int gameId);
        public abstract int GetClientId();
        public abstract void SendLobbyChatMessage(string messageText);
        public abstract void SendLobbyGameChatMessage(string messageText, int gameId);
        public abstract void SendSceneChatMessage(string chatMessage);
        public abstract void RequestLobbyGameList();
        public abstract void RequestLobbyPlayerList();
        public abstract void ChooseLobbyGameCharacter(string unitProfileName, int gameId, string appearanceString, List<SwappableMeshSaveData> swappableMeshSaveData);
        public abstract void RequestStartLobbyGame(int gameId);
        public abstract void RequestJoinLobbyGameInProgress(int gameId);
        public abstract void ToggleLobbyGameReadyStatus(int gameId);
        public abstract void InteractWithOption(UnitController sourceUnitController, Interactable targetInteractable, int componentIndex, int choiceIndex);
        public abstract void RequestSetPlayerCharacterClass(Interactable interactable, int componentIndex);
        public abstract void SetPlayerCharacterSpecialization(Interactable interactable, int componentIndex);
        public abstract void RequestSetPlayerFaction(Interactable interactable, int componentIndex);
        public abstract void RequestLearnSkill(Interactable interactable, int componentIndex, int skillId);
        public abstract void RequestSendMail(Interactable interactable, int componentIndex, MailMessageRequest sendMailRequest);
        public abstract void RequestAcceptQuest(Interactable interactable, int componentIndex, Quest quest);
        public abstract void RequestCompleteQuest(Interactable interactable, int componentIndex, Quest quest, QuestRewardChoices questRewardChoices);
        public abstract void SellVendorItem(Interactable interactable, int componentIndex, long itemInstanceId);
        public abstract void BuyItemFromVendor(Interactable interactable, int componentIndex, int collectionIndex, int itemIndex, string resourceName);
        public abstract void RequestSpawnUnit(Interactable interactable, int componentIndex, int unitLevel, int extraLevels, bool useDynamicLevel, string unitProfileName, string unitToughnessName);
        public abstract void RequestTurnInDialog(Interactable interactable, int componentIndex, Dialog dialog);
        public abstract void RequestTurnInQuestDialog(Dialog dialog);
        public abstract void TakeAllLoot();
        public abstract void RequestTakeLoot(int lootDropId);
        public abstract void RequestBeginCrafting(Recipe recipe, int craftAmount);
        public abstract void RequestCancelCrafting();
        public abstract void RequestUpdatePlayerAppearance(Interactable interactable, int componentIndex, string unitProfileName, string appearanceString, List<SwappableMeshSaveData> swappableMeshSaveData);
        public abstract void RequestChangePlayerName(Interactable interactable, int componentIndex, string newName);
        public abstract void RequestSpawnPet(UnitProfile unitProfile);
        public abstract void RequestDespawnPet(UnitProfile unitProfile);
        public abstract void RequestSceneWeather();
        public abstract void RequestLoadPlayerCharacter(int playerCharacterId);
        public abstract void AcceptCharacterGroupInvite(int inviteGroupId);
        public abstract void DeclineCharacterGroupInvite();
        public abstract void RequestLeaveCharacterGroup();
        public abstract void RequestRemoveCharacterFromGroup(int playerCharacterId);
        public abstract void RequestInviteCharacterToGroup(int playerCharacterId);
        public abstract void RequestInviteCharacterToGroup(string characterName);
        public abstract void RequestDisbandCharacterGroup(int characterGroupId);
        public abstract void RequestPromoteCharacterToLeader(int characterId);
        public abstract void RequestBeginTrade(int characterId);
        public abstract void RequestDeclineTrade();
        public abstract void RequestAcceptTrade();
        public abstract void RequestAddItemsToTradeSlot(int buttonIndex, List<long> itemInstanceIdList);
        public abstract void RequestAddCurrencyToTrade(CurrencyNode currencyNode);
        public abstract void RequestConfirmTrade();
        public abstract void RequestCancelTrade();
        public abstract void RequestUnconfirmTrade();
        public abstract void RequestDeleteMailMessage(int messageId);
        public abstract void RequestTakeMailAttachments(int messageId);
        public abstract void RequestTakeMailAttachment(int messageId, int attachmentSlotId);
        public abstract void RequestMarkMailAsRead(int currentMessageId);
        public abstract void RequestListAuctionItems(Interactable interactable, int componentIndex, ListAuctionItemRequest listAuctionItemRequest);
        public abstract void RequestCancelAuction(int auctionItemId);
        public abstract void RequestBuyAuctionItem(int auctionItemId);
        public abstract void RequestSearchAuctions(Interactable interactable, int componentIndex, string searchText, bool onlyShowOwnAuctions);
        public abstract void DeclineGuildInvite();
        public abstract void AcceptGuildInvite(int inviteGuildId);
        public abstract void RequestLeaveGuild();
        public abstract void RequestInviteCharacterToGuild(int characterId);
        public abstract void RequestInviteCharacterToGuild(string characterName);
        public abstract void RequestRemoveCharacterFromGuild(int characterId);
        public abstract void RequestDisbandGuild(int guildId);
        public abstract void RequestCreateGuild(Interactable interactable, int componentIndex, string guildName);
        public abstract void CheckGuildName(Interactable interactable, int componentIndex, string guildName);
        public abstract void AcceptFriendInvite(int inviteCharacterId);
        public abstract void DeclineFriendInvite(int inviteCharacterId);
        public abstract void RequestInviteCharacterToFriendList(int characterId);
        public abstract void RequestInviteCharacterToFriendList(string characterName);
        public abstract void RequestRemoveCharacterFromFriendList(int characterId);
        public abstract void RequestPromoteGuildCharacter(int characterId);
        public abstract void RequestPromoteGroupCharacter(int characterId);
        public abstract void RequestDemoteGroupCharacter(int characterId);
        public abstract void RequestDemoteGuildCharacter(int characterId);

        // server functions
        public abstract void StartServer(ushort port);
        public abstract void StopServer();
        public abstract void KickPlayer(int clientId);
        public abstract string GetClientIPAddress(int accountId);
        public abstract void AdvertiseCreateLobbyGame(LobbyGame lobbyGame);
        public abstract void AdvertiseCancelLobbyGame(int gameId);
        public abstract void AdvertiseAccountJoinLobbyGame(int gameId, int accountId, string userName);
        public abstract void AdvertiseAccountLeaveLobbyGame(int gameId, int accountId);
        public abstract void AdvertiseSendLobbyChatMessage(string messageText);
        public abstract void AdvertiseSendLobbyGameChatMessage(string messageText, int gameId);
        public abstract void AdvertiseSendSceneChatMessage(string messageText, int accountId);
        public abstract void AdvertiseLobbyLogin(int accountId, string userName);
        public abstract void AdvertiseLobbyLogout(int accountId);
        public abstract void SetLobbyGameList(int accountId, List<LobbyGame> lobbyGames);
        public abstract void SetLobbyPlayerList(int accountId, Dictionary<int, string> lobbyPlayers);
        public abstract void AdvertiseChooseLobbyGameCharacter(int gameId, int accountId, string unitProfileName);
        public abstract void StartLobbyGame(int gameId);
        public abstract void AdvertiseJoinLobbyGameInProgress(int gameId, int accountId, string sceneResourceName);
        public abstract void AdvertiseSetLobbyGameReadyStatus(int gameId, int accountId, bool ready);
        public abstract int GetServerPort();
        public abstract void AdvertiseUnloadScene(int accountId);
        public abstract void ReturnObjectToPool(GameObject returnedObject);
        //public abstract void AdvertiseAddSpawnRequest(int accountId, SpawnPlayerRequest loadSceneRequest);
        public abstract UnitController SpawnCharacterPrefab(CharacterRequestData characterRequestData, Transform parentTransform, Vector3 position, Vector3 forward, Scene scene);
        public abstract GameObject SpawnModelPrefabServer(GameObject prefab, Transform parentTransform, Vector3 position, Vector3 forward);
        public abstract void AdvertiseMessageFeedMessage(int accountId, string message);
        public abstract void AdvertiseSystemMessage(int accountId, string message);
        public abstract void AdvertiseAddToBuyBackCollection(UnitController sourceUnitController, int accountId, Interactable interactable, int componentIndex, InstantiatedItem newInstantiatedItem);
        public abstract void AddAvailableDroppedLoot(int accountId, List<int> lootDropIds);
        public abstract void AddLootDrop(int accountId, int lootDropId, long itemInstanceId);
        public abstract void AdvertiseTakeLoot(int accountId, int lootDropId);
        public abstract void SpawnPlayer(int accountId, CharacterRequestData characterRequestData, Vector3 position, Vector3 forward, string sceneName);
        public abstract Scene GetAccountScene(int accountId, string sceneName);
        public abstract void AdvertiseAddSpawnRequest(int accountId, SpawnPlayerRequest loadSceneRequest);
        public abstract void AdvertiseEndWeather(int sceneHandle, WeatherProfile profile, bool immediate);
        public abstract void AdvertiseChooseWeather(int sceneHandle, WeatherProfile profile);
        public abstract void AdvertiseStartWeather(int sceneHandle);
        public abstract void AdvertiseLoadCutscene(Cutscene cutscene, int accountId);
        public abstract void AdvertiseJoinMMOGameInProgress(int accountId);
        public abstract void AdvertiseAddCharacterToGroup(int accountId, int characterGroupId, CharacterGroupMemberNetworkData characterGroupMemberNetworkData);
        public abstract void AdvertiseCharacterGroup(int accountId, CharacterGroupNetworkData characterGroupNetworkData);
        public abstract void AdvertiseRemoveCharacterFromGroup(int accountId, int characterId, int characterGroupId);
        public abstract void AdvertiseRemoveCharacterFromGuild(int accountId, int characterId, int guildId);
        public abstract void AdvertiseCharacterGroupInvite(int invitedAccountId, int characterGroupId, string leaderName);
        public abstract void AdvertiseDisbandCharacterGroup(int accountId, int characterGroupId);
        public abstract void AdvertisePlayerNameNotAvailable(int accountId);
        public abstract void AdvertiseLoadCharacterList(int accountId, List<PlayerCharacterSaveData> playerCharacterSaveDataList);
        public abstract void AdvertiseDeclineCharacterGroupInvite(int leaderAccountId, string decliningPlayerName);
        public abstract void AdvertisePromoteGroupLeader(int accountId, int characterGroupId, int newLeaderCharacterId);
        public abstract void AdvertiseRenameCharacterInGroup(int accountId, int groupId, int characterId, string newName);
        public abstract void AdvertiseGroupMessage(int accountId, int characterGroupId, string messageText);
        public abstract void AdvertiseGuildMessage(int accountId, int guildId, string messageText);
        public abstract void AdvertisePrivateMessage(int targetAccountId, string messageText);
        public abstract void AdvertiseAcceptTradeInvite(int sourceAccountId, int targetCharacterId);
        public abstract void AdvertiseDeclineTradeInvite(int sourceAccountId);
        public abstract void AdvertiseRequestBeginTrade(int targetAccountId, int sourceCharacterId);
        public abstract void AdvertiseAddItemsToTargetTradeSlot(int targetAccountId, int buttonIndex, List<long> itemInstanceIdList);
        public abstract void AdvertiseAddCurrencyToTrade(int targetAccountId, int amount);
        public abstract void AdvertiseCompleteTrade(int accountId);
        public abstract void AdvertiseCancelTrade(int accountId);
        public abstract void AdvertiseMailMessages(int accountId, MailMessageListBundle mailMessageListResponse);
        public abstract void AdvertiseDeleteMailMessage(int accountId, int messageId);
        public abstract void AdvertiseTakeMailAttachment(int accountId, int messageId, int attachmentSlotId);
        public abstract void AdvertiseTakeMailAttachments(int accountId, int messageId);
        public abstract void AdvertiseConfirmationPopup(int accountId, string messageText);
        public abstract void AdvertiseMailSend(int accountId);
        public abstract void AdvertiseBuyAuctionItem(int accountId, int auctionItemId);
        public abstract void AdvertiseCancelAuction(int accountId, int auctionItemId);
        public abstract void AdvertiseAuctionItems(int accountId, AuctionItemSearchListResult auctionItemListResponse);
        public abstract void AdvertiseListAuctionItems(int accountId);
        public abstract void AdvertiseDisbandGuild(int accountId, int guildId);
        public abstract void AdvertiseDeclineGuildInvite(int leaderAccountId, string playerName);
        public abstract void AdvertiseGuildInvite(int invitedCharacterId, int guildId, string leaderName);
        public abstract void AdvertiseGuild(int accountId, GuildNetworkData guildNetworkData);
        public abstract void AdvertisePromoteGuildLeader(int accountId, int guildId, int newLeaderCharacterId);
        public abstract void AdvertiseRenameCharacterInGuild(int accountId, int guildId, int characterId, string newName);
        public abstract void AdvertiseAddCharacterToGuild(int existingAccountId, int guildId, GuildMemberNetworkData guildMemberNetworkData);
        public abstract void AdvertiseGuildNameAvailable(int accountId);
        public abstract void AdvertiseCharacterGroupMemberStatusChange(int accountId, int characterGroupId, int playerCharacterId, CharacterGroupMemberNetworkData characterGroupMemberNetworkData);
        public abstract void AdvertiseGuildMemberStatusChange(int accountId, int guildId, int playerCharacterId, GuildMemberNetworkData guildMemberNetworkData);
        public abstract void AdvertiseAddFriend(int sourceCharacterAccountId, CharacterSummaryNetworkData characterSummaryNetworkData);
        public abstract void AdvertiseRemoveCharacterFromFriendList(int targetCharacterAccountId, int sourceCharacterId);
        public abstract void AdvertiseDeclineFriendInvite(int friendAccountId, string characterName);
        public abstract void AdvertiseFriendInvite(int invitedAccountId, int sourceCharacterId, string sourceCharacterName);
        public abstract void AdvertiseFriendList(int accountId, FriendListNetworkData friendListNetworkData);
        public abstract void AdvertiseRenameCharacterInFriendList(int targetAccountId, int characterId, string newName);
        public abstract void AdvertiseFriendStateChange(int targetAccountId, int playerCharacterId, CharacterSummaryNetworkData characterSummaryNetworkData);
        public abstract void UnloadScene(int sceneHandle);
        public abstract void LoadExistingScene(int accountId, int sceneHandle);
        public abstract void LoadNewScene(int accountId, int playerCharacterId, SceneInstanceType dungeon, SceneNode sceneNode);
        public abstract void LoadNewLobbyGameScene(int accountId, LobbyGame lobbyGame, SceneNode sceneNode);
    }

}